* Personajes prototípicos de los cuentos infantiles

** Cuentos con brujas

- propósito didáctico: que los niños conozcan mucho del personaje para que tengan oportunidad de anticipar sus acciones, sus conflictos o sus palabras y, de ese modo, leer mejor, saber qué puede decir y corroborarlo en el texto.
- Los cuentos tradicionales ofrecen una organización canónica que permite, aún a lectores pequeños, prever las acciones y el desarrollo de la trama. Los niños pueden anticipar rápidamente cómo comienzan, cómo será el final –casi siempre feliz-, el comportamiento de los personajes, que sin demasiadas motivaciones implícitas actúan como ayudantes u oponentes de aquellos que llevan adelante la acción. Los escenarios representados (los bosques, los castillos, los países lejanos) constituyen espacios prototípicos descriptos con pocas pinceladas que funcionan como marco estable de las acciones.

*** Producto final: Album de Brujas

*** Momentos del proyecto
- Los momentos son instancias donde prevalece lo que se enuncia en el título, pero en los mismos siempre se alternan situaciones de lectura y de escritura.
- Lectura por parte del maestro y apertura de intercambio
- Lectura por si mismo
- Lecturas para saber más sobre brujas con toma de notas
- Escritura a partir de las lecturas realizadas. Escritura de textos intermedios ya sean “más despejados” o “más extensos”.
- Relectura de los cuentos y las escrituras intermedias en función del producto seleccionado. Escrituras para publicar. Edición del producto.

*** Cuentos a leer
- Hansel y Gretel
- La sirenita
- La bella durmiente
- La bruja Baba Yaga
- Basilisa la hermosa
- Disculpe ¿es usted una bruja?
- Cuentos con brujas
- Niños, las brujas no existen
- La bruja Berta
- Yo y mi gato
- Blancanieves



*** Secuencia
- Previo a la secuencia preparar:
- Afiche con los títulos, autor. Desordenados (Agenda de lectura). Dejar espacio par poner la fecha Preparar una agenda impresa, igual a la del ambiente para que vayan marcando a medida que se leen los cuentos.

**** Clase 1: Entrando en tema. Hansel y Gretel
Presentación del tema: "Vamos a leer muchos cuentos de brujas, para escribir lo que sabemos de cada una y armar un album de estos personajes.”
Lectura por parte del maestro. “Hoy les voy a leer Hansel y Gretel, un cuento que me contaron cuando era chico. Es una historia que ha sido contada muchas veces.” Los maestros leen cada cuento respetando cada texto y adecuando el tono y volumen de su voz a las circunstancias del relato.
Intercambio entre lectores. hacer planteos u observaciones que permitan releer pasajes con distintos motivos: por ejemplo, corroborar interpretaciones, revivir escenas o apreciar la manera en que están escritas: ¿Qué parte de la historia les dio más miedo?, ¿Por qué cuando llegan a la casa me sigue dando la sensación de que no están a salvo” ¿En qué momento se dieron cuenta de que la vieja era una bruja?
Los niños marcan en la agenda el título leído. Y escribirán un breve apreciación o comentario del cuento
**** Clase 1: Hansel y Gretel 2
- Presentación del cuadro
- Lectura por parte del maestro.
- Escritura por parte del maestro en afiche.
- Dibujo y escritura para el album

**** Clase 2: La sirenita
- Lectura por parte del maestro. “Hoy les voy a leer La sirenita, un cuento del que hicieron una película, ¿la vieron?. Esta es otra historia que ha sido contada muchas veces.” 
  Los maestros leen el cuento respetando cada texto y adecuando el tono y volumen de su voz a las circunstancias del relato.
- Intercambio entre lectores. Hacer planteos u observaciones que permitan releer pasajes con distintos motivos: por ejemplo, corroborar interpretaciones, revivir escenas o apreciar la manera en que están escritas: ¿Qué parte de la historia les dio más miedo?, ¿Cómo es esta bruja? ¿Qué cosas le pide la bruja a cambio del deseo de la sirenita? en esta versión de la sirenita no la llaman “bruja”¿ de qué otra manera se refieren a ella? (hechicera)
 Los niños marcan en la agenda el título leído. Y escribirán un listado de personajes del cuento por si mismo, luego revisaremos cómo se escribieron los nombres y ese listado luego quedará en el ambiente alfabetizador.

**** Clase 3: La sirenita
- Lectura por parte del maestro.
- Lectura con los estudiantes de fragmento donde aparece la bruja. Ubicar ¿Dónde dice?
- Escritura por parte de los estudiantes: los estudiantes completarán en parejas la fila del cuadro para que luego repasar que vamos a dejar en él.
- Momento de reflexión : retomando ciertos aspectos del sistema de escritura.
 “Encontré escrito brujas de tres maneras diferentes, se las muestro: BUJAS, BJAS, BRUJAS
 ¿Buscamos en La Bruja Berta para ver cómo se escribe?”
- puesta en común del llenado de ficha para que el maestro complete el cuadro.
- Dibujo y escritura para el album

**** Clase 4: La bella durmiente
- Lectura por parte del maestro del cuento “La bella durmiente”.
- Intercambio entre lectores. 
- Seleccionar y releer algunos pasajes… 

>"Estaba por anunciar su ofrenda la número doce cuando un silencio de muerte invadió el salón del palacio. Las puertas se abrieron de par en par y dejaron pasar a la vieja hada que no había sido invitada. Quería vengarse por el desaire sufrido y, sin saludar ni mirar a nadie, extendió la huesuda mano de largas uñas y exclamó con voz ronca:
>– La princesa se pinchará con el huso de una rueca al cumplir los quince años y caerá muerta.
>Sin decir una palabra más, dio media vuelta y dejó el salón”.

- Agenda de lectura: localizar y marcar el cuento en la agenda de lectura.

**** Clase 5: La bella durmiente

- Lectura: marcar dónde dice y aprender de memoria el verso.

|fragmento despejado de maldición y príncipe|
|LA PRINCESA SE PINCHARÁ CON EL HUSO DE UNA RUECA AL CUMPLIR LOS QUINCE AÑOS Y CAERÁ MUERTA.|
|YO NO TEMO A LAS ESPINAS. QUIERO VER A LA BELLA DURMIENTE.|

|fragmento de durmientes|
|SE DURMIERON LOS CABALLOS EN EL ESTABLO, LOS PERROS EN EL PATIO, LAS PALOMAS EN EL PALOMAR, LAS MOSCAS EN LAS PAREDES. LA LLAMA DEL FUEGO DEL HOGAR QUEDÓ INMÓVIL Y DORMIDA Y LOS MANJARES DE LA COCINA QUEDARON A MEDIO ASAR. EL COCINERO, QUE EN AQUEL MOMENTO LEVANTABA El BRAZO PARA PEGARLE AL AYUDANTE QUE HABÍA HECHO UNA TRAVESURA, SE QUEDÓ DORMIDO CON EL BRAZO EN ALTO. LA COCINERA SE DURMIÓ DESPLUMANDO A UNA GALLINA.|

- Escritura:
  - Listado en cuadro quién y cómo quedan luego de la maldición.
    - PALOMAS
    - MOSCAS
    - COCINERO
    - COCINERA
- Dictado al maestro del cuadro de características con las brujas.
- Completar figura para el álbum.




**** Blancanieves 7.
***** Clase 1
- Lectura por parte del docente.
- Apertura de un espacio de intercambio:
  - Discutir en tornos a las características  de  la bruja y las acciones que lleva adelante porque no tolera que la aventaje en belleza.
  - Relacionar ese tema con los intentos de la bruja para matar a Blancanieves.
  - Reflexionar en torno a cómo es la princesa (no solo físicamente sino también lo que siente, las emociones, su inocencia)
  - Discutir cómo es que la bruja se da cuenta que sus intentos para matar a Blancanieves no funcionaron. 
  - Buscar algunas metáforas o comparaciones  propias del lenguaje escrito para reflexionar en torno a las sensaciones que producen,
  - Recuperar en el texto cómo se va incrementando el enojo la bruja.
- Escritura por sí mismo:
  - Fichar el libro con comentario personal.
***** Clase 2
- Lectura por sí mismo:
 - Primera situación de lectura por sí mismo: lectura exploratoria.
 - Localizar la primera vez que la bruja le pregunta al espejo quién es la más hermosa/ y la respuesta. Ensayar la lectura en voz alta.  en la respuesta del espejo;  hacer localizaciones. Buscar todas las veces que se repite la frase y discutir por qué. En la respuesta del espejo buscar las variaciones de lo que va diciendo. 
  - Localizar el fragmento en el que Blancanieves cuando entra a la casa de los enanos. Lo relee el maestro y luego comparte la lectura con los niños deteniéndose para que ellos complete con lo que dirá.  
  - Otra: localizar el apartado en el que los enanos entran a la casa y se encuentran con que alguien había estado allí. Lo localizan los niños, el maestro relee y pide que localicen alguna de las preguntas y algunos de los objetos.   
  - Localizar el deseo de madre acerca de cómo quería que fuera su hija; se reitera dos veces esa frase.
- Retomar algunas  situaciones de lectura del cuadernillo:
  - Los distintos tipos de manzanas: manzana envenenada; manzana endulzada;  etc. (para localizar)
- ¿Quién dijo?( (fragmento de los enanos)
- Los elementos con los que la bruja intenta matar a Blancanieves.

- Escritura
  - Cómo es Blancanieves.
  - Revisar la escritura de “negro” y “sangre”: levantar distintas realizaciones de esas palabras para discutir el pizarrón. 
  - Pensar otras palabras que presentan la misma dificultad que quedan como listas en el ambiente
  - Cada uno corrige en su propia escritura “negro y sangre” con otro color. 

- Trabajar la palabra “espejito” con letras justas para luego escribir la “frase célebre” de la bruja. La idea es que les sirva como palabra segura. Plantear el paradigma lexical de esa palabra (espejo/espejado) para que los que producen escrituras silábicas puedan incorporar más letras teniendo un modelo y los que ya escriben de manera alfabetizada puedan tomar el rasgo ortográfico.

- Otra de reflexión:
Silla/sillita



- Escritura de episodio: episodio de la manzana
  - Relectura por parte del maestro del episodio para construir el plan de escritura.
  - Enojo de la bruja ante el fracaso de plan para matarla
  - Piensa y prepara un nuevo plan. Preparación de la manzana
  - Camino hacia la casa de los enanos
  - Encuentro y convencimiento de la bruja para que Blancanieves acepte la manzana.
  - Resultado del plan/muerte de Blancanieves

- Darle el siguiente pie:
- Dictado al maestro:
- Completamiento del cuadro.



* Bibliografía
