#+OPTIONS: tex:t
#+ODT_STYLES_FILE:"/home/alvar/Dropbox/2016/org/opensans.odt"
#+DESCRIPTION:
#+KEYWORDS:
#+SUBTITLE:

* Pausa Evaluativa 2do Diciembre 2016
** Propuestas de lectura
- Estas son recomendaciones, escritas por otros nenes de 2do,  de cuentos que leímos en el aula. Leelas y uní con flechas el título que corresponda
  - Clementina Queridita
  - Un gato como cualquiera
  - El patito feo
  - Reseña intrusa de alguno de Roldán
- Este es un fragmento del cuento "El patito feo" releélo y respondé la siguiente pregunta:
  ¿Cómo eran las aves que vió el patito? si querés podés marcarlo en el texto.

** Situaciones de Escritura
- Este texto lo escribió una nena de segundo grado. La maestra le subrayó las palabras que tiene que revisar. Coregí y escribí las palabras abajo correctamente

| El _pero_ se _rretiró_ sin tocarlo. Luego _elpatito_ llegó a una cabaña donde vivía una anciana con _sugato_ y su _gayina_. Ella los _cería_ como hijos. |

- Escribí lo que le ocurió al patito en la casa del campesino que lo salvó de quedarse congelado.
A la mañana siguiente, muy temprano, lo encontró un campesino.........
- Escribí los títulos que la maestra te dicta
  - Historia de un amor exagerado
  - Julia la de los pelos largos
  - Un gato como cualquiera
* Pausa Evaluativa 1ro Diciembre 216
** Propuestas de lectura
- Este es una parte del dialogo entre la reina y el espejo. Leélo y marcá quien lo dijo
 
| REINA Y SEÑORA TU ERES DE TODAS LA MAS HERMOSA |
| LA REINA MALVADA                               |
| ESPEJO                                         |
| ENANITO                                        |
- Este es un fragmento del cuento (llegada a la casa de los enanos) Blancanieves marcá dónde dice pan, etc
** Propuestas de escritura
- Este es uno de los engaños de la reina a Blancanieves, escribí todo lo que pasó en esta escena
- Escribí las palabras que la maestra te dicta.
  - Bruja
  - Verdura
  - Manzana
  - Enanito
  - Pan
