
#+TITLE: Seguimiento de autor
#+AUTHOR: Alvar Maciel
* Índice
:PROPERTIES:
:ID:       5ae2cb7f-97a4-40ae-8a62-f1f4eb46d4be
:END:
- [[SeguimientoAutorGMontes.org#producto][Producto]]
- [[SeguimientoAutorGMontes.org#momentos][Momentos]]
- [[SeguimientoAutorGMontes.org#recorrido-posible][Recorrido posible]]
- [[SeguimientoAutorGMontes.org#propuestas-de-trabajo-con-la-biografía][Propuestas de trabajo con la Biografía]]
- [[SeguimientoAutorGMontes.org#situaciones-de-lectura][Situaciones de lectura]]
- [[SeguimientoAutorGMontes.org#propuestas-de-escritura][Propuestas de escritura]]
- [[SeguimientoAutorGMontes.org#secuencia-de-actividades][Secuencia de actividades]]
  - [[SeguimientoAutorGMontes.org#historia-de-un-amor-exagerado][Historia de un amor exagerado]]
  - [[SeguimientoAutorGMontes.org#do%C3%B1a-clementina-querida-achicadora][Doña Clementina queridita, la achicadora]]
  - [[SeguimientoAutorGMontes.org#más-chiquito-que-una-arveja-más-grande-que-una-ballena][Más chiquito que una arveja, más grande que una ballena]]
  - [[SeguimientoAutorGMontes.org#un-gato-como-cualquiera][Un gato como cualquiera]]

* Graciela Montes
:PROPERTIES:
:ID:       a7f87cc7-0a9f-4990-8707-e4adaf2dc037
:END:
** Producto
:PROPERTIES:
:ID:       fbfc3b42-d002-414c-91d4-6e34cc513413
:END:
- [X] Recomendaciones de diferentes obras de la autora. Los chicos en grupos las escriben y dibujan, las grabamos y las subimos. Cual book trailer
- [ ] Galería de personajes
** Momentos
:PROPERTIES:
:ID:       4e229e84-d691-4be1-a0e3-849bbd8bc847
:END:
- [ ] Circulación de recomendaciones para elaborar la agenda:
- [ ] Lectura por parte del maestro
- [ ] Lectura por parte de los niños
- [ ] Lectura domiciliaria
- [ ] Lectura de biografías
- [ ] Propuestas de escritura
- [ ] Reflexión del lenguaje

** Recorrido posible
:PROPERTIES:
:ID:       e02267da-8559-43de-a127-629f8e2355c8
:END:
- Historia de un amor exagerado 5 - Bs. As. Ed. Colihue, 1987. Colección Libros del Malabarista.
- Doña Clementina Queridita, la achicadora- Bs. As., Ed. Colihue, 1985. Colección Libros del Malabarista. Doña Clementina Queridita, la achicadora 3 ; Historia de un Ramón, un salmón y tres deseos; Julia la de los pelos largos 4 ; La casa más abrigada del mundo.
- El club de los perfectos- Bs. As. Ed. Colihue, 1989. Colección El Pajarito Remendado.
- La familia Delasoga- Bs. As. Ed. Colihue, 1985. Colección El Pajarito Remendado.
- Más chiquito que una arveja, más grande que una ballena- Bs. As. Ed. Sudamericana, 1989. Colección Pan Flauta.
- Un gato como cualquiera- Bs. As. Ed. Colihue, 1984. Colección El Pajarito Remendado Un gato como cualquiera; Bicho raro.
- Las velas malditas- Bs. As. Ed. Alfaguara, 1994. Colección Infantil.
- Irulana y el Ogronte- Bs. As. Gramón-Colihue, 1995. Colección Los cuentos del Ratón Feroz.
- Clarita se volvió invisible – Bs. As. Libros del Quirquincho, 1989. Colección La Ratona cuentacuentos.
- La batalla de los monstruos y las hadas 6 . Aique Grupo Editor, 1994. Reeditado: Editorial Alfaguara, 2001. Colección Alfaguara Infantil; serie Naranja.
- Tengo un monstruo en el bolsillo 7 . Libros del Quirquincho, 1988. Colección Serie Negra. Reeditado en: Editorial Sudamericana, 1999. Colección Especiales.
** Propuestas de trabajo con la Biografía
:PROPERTIES:
:ID:       3e38db5f-2403-4f42-84d8-5ec0ce84e9b1
:END:
- Lectura del maestro de diverso material biográfico sobre la autora.
- Escritura por sí mismo (individualmente en parejas o en pequeños grupos) de datos de la autora a partir de lo que el maestro lee y cuenta.
- Lectura por sí mismo (individual o en parejas) de una biografía que haya leído el maestro.
- Lectura por sí mismo (individual o en parejas) de una biografía que no haya leído el maestro.
- Dictado al docente de datos de la vida y la obra de la autora en cuestión.
** Situaciones de lectura
:PROPERTIES:
:ID:       1be5c6a1-48ff-4b36-9221-7b5ed8d2cffa
:END:
- Lectura por parte del maestro
- Lectura por si mismo, textos conocidos o más despejados como Clarita se volvió invisible o Clarita se fue a la China, El ratón feroz o El ratón feroz vuelve al ataque.
- Historia de un Ramón, un salmón y tres deseos o Julia la de los pelos largos, pueden ser previstos para niños que leen convencionalmente.
  - cada pequeño grupo comenta el cuento leído al resto de la clase por ejemplo.
- 
** Propuestas de escritura
:PROPERTIES:
:ID:       bfee4c09-699e-4a97-972b-b44a6fda43ed
:END:
- Registrar obras leídas y por leer,
- personajes, caracterizaciones de los mismos,
- modos de decir,
- expresiones que se repiten,
- diálogos o fragmentos significativos,
- comparaciones y relaciones entre cuentos,
- notas sobre la vida y la obra de la autora.
** Secuencia de actividades
:PROPERTIES:
:ID:       1dfa9a32-c565-4e20-97e2-0650f3c945c0
:END:
*** Agenda de lectura
:PROPERTIES:
:ID:       69c4c36f-364b-4c31-9e8d-58de9c776086
:END:
- Lectura por parte del maestro de algunas recomendaciones
- distribución y lectura por parte de los estudiantes de recomendaciones de libros que formarán parte de la agenda de lectura, mezclar en esta selección recomendaciones de otros libros
- elaboración de la selección de forma grupal el afiche
  - Luego se le entregará a cada estudiante una copia de la selección a modo de agenda para ir registrando lo leído.
*** Historia de un amor exagerado 
:PROPERTIES:
:ID:       5dbf16a3-fc58-4b21-8e69-dc561aaee47b
:END:
- Mínimo dos lecturas por semana
- Lectura por parte del maestro de capítulo 1
  - Leer el prólogo, mostrar la foto e intercambiar con los estudiantes sobre la relación entre Chacho y Graciela
- Intercambio entre lectores
  - ¿Cómo es Florida?
  - ¿Qué tiene?
  - ¿Cómo se sintió Santiago cuando vió a Teresita Yoon?
  - ¿Cómo te diste cuenta?
  - ¿Por qué se dirá que Santiago es exagerado?
  - ¿Cómo dice la autora esto?
- Escrituras intermedias
  - Listado características de Florida
  - Listado de personajes
  - Características de Santiago y Teresita
- Lectura por parte del maestro de Capítulo 2
  - Intercambio entre lectores
- Escritura intermedia con plan de escritura de lo que ocurrió en el capítulo
- Lectura por si mismos del Capítulo 3
  - Intercambio entre lectores
    - ¿Como reaccionaba la gente al amor de Santiago y Teresita? (Marcar las dos reacciones)
    - ¿A dónde fueron los nenes? Reponer que y como es el tigre
    - ¿Cómo reacciona Santiago al secreto de Teresita? (Marcar)
    - ¿Y Teresita? (Marcar)
    - En este capítulo, hay varios elementos que nos anticipan que algo trágico va a pasar, cuales son esos elementos como me voy dando cuenta que algo malo va a pasar. (Marcar)
  - Escritura Intermedia, copia con sentido para saber como dice.
    - Vamos a retomar las marcas que hicimos en el texto para ver como dice la autora algunas cosas:
      - ¿Cuáles son los indicios de la tragedia?
      - ¿Que frases o palabras nos indican que a algunas personas no les gustaba el amor de los chicos y a otros sí?
- Lectura por si mismos Capítulo 4
  - Intercambio entre lectores
  - Escritura intermedia: Que cosas le mandó a Teresita (Armar plan de escritura)
- Lectura por parte del maestro Cap 5 y 6
  - Intercambio entre lectores
    - ¿Cómo terminó la historia?
  - Afiche con personajes y situaciones (cón dibujos, cual galería)

*** Doña clementina querida achicadora
:PROPERTIES:
:ID:       a8d911b3-637b-4f95-b38c-3dcdb50e7df4
:END:
- Lectura a través del docente 
  - El maestro contextualiza la lectura del cuento comentando algunos datos de la biografía y bibliografía de la autora para luego leer la carta a los niños que presenta el libro donde se encuentra el cuento “Doña Clementina Queridita, la Achicadora”.
  - El maestro lee el cuento a los niños sin interrupciones.
- Espacio de Intercambio entre lectores después de la lectura
  - ¿Qué fue lo que más les sorprendió de este cuento?
  - Parece que Doña Clementina también estaba sorprendida y muy preocupada… ¿Por qué?
  - ¿Por qué les parece que a Doña Clementina la llaman “Queridita”?
  - ¿Cuándo se convirtió en Achicadora? Volvamos a leerlo…
  - ¿Qué hizo Doña Clementina cuando se dio cuenta que Polidoro, el gato, se había achicado al tamaño de una pelusa?
  - Finalmente en la farmacia ¿Consiguió el remedio para curar al gato del achique?
  - A mí me gusta la parte en que achica a Oscarcito el día de su cumpleaños, estaba tan ansioso por soplar las velitas y justo pasó lo que pasó ¿Les leo otra vez esa parte?
  - ¿En el barrio se dieron cuenta enseguida de los achiques de Doña Clementina?
  - ¿Por qué les parece qué en el cuento dice que “se dio cuenta de que las hueveras eran muy útiles para guardar achicados”?
  - ¿Cómo cuidaba Doña Clementina a cada uno de sus achicados?
  - ¿Por qué será que Doña Clementina le dice al gato: “Gatón! Gatote! Gatazo!?
  - Los lectores ¿Cuándo comenzamos a darnos cuenta del poder de sus palabras? ¿Se acuerdan en que parte de la historia? Les voy a leer algunos pasajes que me parece que nos ayudarán a decidir. Ustedes me avisan.
- Lectura por sí mismo
  - proponer que los niños sigan la lectura en parejas o tríos, centrándose en profundidad en la lectura de algunos párrafos de la historia.
  - ¿Cuándo se produjo el primer achique? (Pág. 16)
  - Lean y copien la lista de cosas que achicó Doña Clementina (Pág. 21)
  - Busquen y lean ¿Cómo cuidaba Doña Clementina a sus achicados? (Pág. 23)
  - Busquen y lean ¿Cuándo descubrió Doña Clementina que podía hacer crecer a sus achicados? (Pág. 24/ 25)
  - La maestra solicita a los niños que localicen algún pasaje del texto. Por ejemplo: “Aquí aparece algo escrito en negrita” ¿Qué les parece que indica?
- Escritura por sí mismo
  - ¿Qué le contarías a otro chico que no leyó el cuento para que sepa cómo es Doña Clementina?
  - ¿Por qué le dicen “Queridita”? Escribilo cómo lo dice en el cuento.
  - ¿Cómo era Doña Clementina de chica?
  - ¿Cómo fue que Doña Clementina descubrió el antídoto para la enfermedad del achicamiento?
  - Escribí ¿Cómo cuidaba Doña Clementina a cada uno de sus achicados?
  - Contale a otro chico que no leyó el cuento cómo se solucionó la enfermedad de los achicados en el barrio de Florida. -No te olvides ningún detalle de cómo se solucionó el problema.
  - Escribí ¿Qué hicieron los achicados cuando volvieron a tener su tamaño real?
  - Luego de leer la carta a los niños que Graciela Montes incluye antes del cuento, le proponemos a los niños que en parejas le escriban una carta de respuesta a la autora.
  - Escribí el o los antídotos para cada uno de estos achiques, tal como lo haría Doña Clementina: Gatito, Don Ramoncito, Oscarcito, Frasquito de jarabe, Manzanita, Sillita, Arbolito, Librito de cuentos, siete velitas.

*** Más chiquito que una arveja, más grande que una ballena
:PROPERTIES:
:ID:       cd8a78d9-f57c-4988-b019-4013d1956ca3
:END:
- Lectura a través del docente 
  - El maestro lee el cuento a los niños sin interrupciones.
- Espacio de Intercambio entre lectores después de la lectura
  - ¿Qué parte les gustó? releer fragmentos
  - Cómo era el gato grande, releer como la autora da ejemplos para imaginarnos lo grande que es.
  - Cómo era el gato chiquito, releer como la autora da ejemplo para imaginarnos lo chiquito que es.
  - ¿Por qué se enfrentaron los gatos?
  - ¿Por qué los vecinos reaccionaro así? ¿Por qué será que se cansaron justo en ese momento?
- Escritura por parte del maestro
  - Retomar las recomendaciones, escribir plan de lectura
    - De que se trata
    - NO CONTAR EL FINAL
    - Invitar y entusiasmar para que quieran leer el cuento.
  - Ahora vamos a escribir la primer recomendación. ¿Cómo la escribiriamos?
*** Un gato como cualquiera
:PROPERTIES:
:ID:       b65bc033-5dff-4369-978c-52f62f27c143
:END:
- Lectura a través del docente 
  - El maestro lee el cuento a los niños sin interrupciones.
- Espacio de Intercambio entre lectores después de la lectura
  - ¿Cómo era el gato de bolsillo? ¿Cómo e dieron cuenta que era chiquito, lo dice en algún momento?
  - ¿Cómo eran los gatos peligrosos? ¿Cómo los describe Anibal Gobi?
  - ¿Cómo imaginaba El Mundo Grande?
- Propuesta de escritura intermedia.
  - Vamos a hacer un ejericio para escribir una descripción. Vamos a escribir cómo son los gatos que tenemos o nos imaginamos
|¡ATENCIÓN!|
|NO ESCRIBIR UNA LISTA|
|INCLUIR LA MAYOR CANTIDAD DE DETALLES|

- Revisión

- Propuesta de Lectura
  - Presentar fragmento con descripción de los mundos
    - ¿Dónde dice como era el bolsillo?
    - ¿Donde dice como era el mundo grande?
    - Transcribir en formato tabla ambos mundos
 
    |Mundo en el bolsillo|Mundo Grande|
    |                    |            |
    
  - Presentar fragmento con descripción de los gatos peligrosos
    - Marcar dónde dice como era el gato de bolsillo
    - Marcar dónde dice cómo eran los gatos peigrosos
    - ¿Qué diferencias había?
- Escritura en parejas
  - Vamos a escribir sólo ¿De qué se trata el cuento?
