# Created 2016-09-30 vie 07:28
#+TITLE: Seguimiento de autor
#+AUTHOR: Alvar Maciel
* Graciela Montes
** Producto
- [X] Recomendaciones de diferentes obras de la autora. Los chicos en grupos las escriben y dibujan, las grabamos y las subimos. Cual book trailer
- [ ] Galería de personajes
** Momentos
- [ ] Circulación de recomendaciones para elaborar la agenda:
- [ ] Lectura por parte del maestro
- [ ] Lectura por parte de los niños
- [ ] Lectura domiciliaria
- [ ] Lectura de biografías
- [ ] Propuestas de escritura
- [ ] Reflexión del lenguaje

** Recorrido posible
- Historia de un amor exagerado 5 - Bs. As. Ed. Colihue, 1987. Colección Libros del Malabarista.
- Doña Clementina Queridita, la achicadora- Bs. As., Ed. Colihue, 1985. Colección Libros del Malabarista. Doña Clementina Queridita, la achicadora 3 ; Historia de un Ramón, un salmón y tres deseos; Julia la de los pelos largos 4 ; La casa más abrigada del mundo.
- El club de los perfectos- Bs. As. Ed. Colihue, 1989. Colección El Pajarito Remendado.
- La familia Delasoga- Bs. As. Ed. Colihue, 1985. Colección El Pajarito Remendado.
- Más chiquito que una arveja, más grande que una ballena- Bs. As. Ed. Sudamericana, 1989. Colección Pan Flauta.
- Un gato como cualquiera- Bs. As. Ed. Colihue, 1984. Colección El Pajarito Remendado Un gato como cualquiera; Bicho raro.
- Las velas malditas- Bs. As. Ed. Alfaguara, 1994. Colección Infantil.
- Irulana y el Ogronte- Bs. As. Gramón-Colihue, 1995. Colección Los cuentos del Ratón Feroz.
- Clarita se volvió invisible – Bs. As. Libros del Quirquincho, 1989. Colección La Ratona cuentacuentos.
- La batalla de los monstruos y las hadas 6 . Aique Grupo Editor, 1994. Reeditado: Editorial Alfaguara, 2001. Colección Alfaguara Infantil; serie Naranja.
- Tengo un monstruo en el bolsillo 7 . Libros del Quirquincho, 1988. Colección Serie Negra. Reeditado en: Editorial Sudamericana, 1999. Colección Especiales.
** Propuestas de trabajo con la Biografía
- Lectura del maestro de diverso material biográfico sobre la autora.
- Escritura por sí mismo (individualmente en parejas o en pequeños grupos) de datos de la autora a partir de lo que el maestro lee y cuenta.
- Lectura por sí mismo (individual o en parejas) de una biografía que haya leído el maestro.
- Lectura por sí mismo (individual o en parejas) de una biografía que no haya leído el maestro.
- Dictado al docente de datos de la vida y la obra de la autora en cuestión.
** Situaciones de lectura
- Lectura por parte del maestro
- Lectura por si mismo, textos conocidos o más despejados como Clarita se volvió invisible o Clarita se fue a la China, El ratón feroz o El ratón feroz vuelve al ataque.
- Historia de un Ramón, un salmón y tres deseos o Julia la de los pelos largos, pueden ser previstos para niños que leen convencionalmente.
  - cada pequeño grupo comenta el cuento leído al resto de la clase por ejemplo.
- 
** Propuestas de escritura
- Registrar obras leídas y por leer,
- personajes, caracterizaciones de los mismos,
- modos de decir,
- expresiones que se repiten,
- diálogos o fragmentos significativos,
- comparaciones y relaciones entre cuentos,
- notas sobre la vida y la obra de la autora.
** Secuencia de actividades
*** Agenda de lectura
- Lectura por parte del maestro de algunas recomendaciones
- distribución y lectura por parte de los estudiantes de recomendaciones de libros que formarán parte de la agenda de lectura, mezclar en esta selección recomendaciones de otros libros
- elaboración de la selección de forma grupal el afiche
  - Luego se le entregará a cada estudiante una copia de la selección a modo de agenda para ir registrando lo leído.
*** Historia de un amor exagerado dos lecturas por semana
- Lectura por parte del maestro de capítulo 1
  - Leer el prólogo, mostrar la foto e intercambiar con los estudiantes sobre la relación entre Chacho y Graciela
- Intercambio entre lectores
  - ¿Cómo es Florida?
  - ¿Qué tiene?
  - ¿Cómo se sintió Santiago cuando vió a Teresita Yoon?
  - ¿Cómo te diste cuenta?
  - ¿Por qué se dirá que Santiago es exagerado?
  - ¿Cómo dice la autora esto?
- Escrituras intermedias
  - Listado características de Florida
  - Listado de personajes
  - Características de Santiago y Teresita
- Lectura por parte del maestro de Capítulo 2
  - Intercambio entre lectores
- Escritura intermedia con plan de escritura de lo que ocurrió en el capítulo
- Lectura por si mismos del Capítulo 3
  - Intercambio entre lectores
    - ¿Como reaccionaba la gente al amor de Santiago y Teresita? (Marcar las dos reacciones)
    - ¿A dónde fueron los nenes? Reponer que y como es el tigre
    - ¿Cómo reacciona Santiago al secreto de Teresita? (Marcar)
    - ¿Y Teresita? (Marcar)
    - En este capítulo, hay varios elementos que nos anticipan que algo trágico va a pasar, cuales son esos elementos como me voy dando cuenta que algo malo va a pasar. (Marcar)
  - Escritura Intermedia, copia con sentido para saber como dice.
    - Vamos a retomar las marcas que hicimos en el texto para ver como dice la autora algunas cosas:
      - ¿Cuáles son los indicios de la tragedia?
      - ¿Que frases o palabras nos indican que s algunas personas no les gustaba el amor de los chicos y a otros sí?
